/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prato_certo;

/**
 *
 * @author fernanda
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    public static String pedidoCliente = "";
    public static double valorTotal = 0.0;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        Buttonpaga = new javax.swing.JButton();
        Buttondele = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textresumo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenucarda = new javax.swing.JMenu();
        CheckBoxstrogo = new javax.swing.JCheckBoxMenuItem();
        CheckBoxbaca = new javax.swing.JCheckBoxMenuItem();
        CheckBoxsopa = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Checkbatapalha = new javax.swing.JCheckBoxMenuItem();
        CheckBoxextra = new javax.swing.JCheckBoxMenuItem();
        CheckBoxbata = new javax.swing.JCheckBoxMenuItem();
        CheckBoxsala = new javax.swing.JCheckBoxMenuItem();
        jMenu12 = new javax.swing.JMenu();
        CheckBoxcoca = new javax.swing.JCheckBoxMenuItem();
        CheckBoxagua = new javax.swing.JCheckBoxMenuItem();
        CheckBoxguarana = new javax.swing.JCheckBoxMenuItem();
        CheckBoxpedras = new javax.swing.JCheckBoxMenuItem();
        CheckBoxnenhu = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu2.setText("jMenu2");

        jMenuItem4.setText("jMenuItem4");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar5.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Buttonpaga.setBackground(new java.awt.Color(153, 255, 153));
        Buttonpaga.setText("Pagar");
        Buttonpaga.addActionListener(this::ButtonpagaActionPerformed);

        Buttondele.setBackground(new java.awt.Color(255, 102, 102));
        Buttondele.setText("Deletar pedido");
        Buttondele.addActionListener(this::ButtondeleActionPerformed);

        Textresumo.setBackground(new java.awt.Color(255, 255, 204));
        Textresumo.setColumns(20);
        Textresumo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Textresumo.setRows(2);
        jScrollPane1.setViewportView(Textresumo);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jMenucarda.setBackground(new java.awt.Color(204, 255, 204));
        jMenucarda.setText("Cardapio");

        CheckBoxstrogo.setText("Strogonoff");
        CheckBoxstrogo.addActionListener(this::CheckBoxstrogoActionPerformed);
        jMenucarda.add(CheckBoxstrogo);

        CheckBoxbaca.setText("Bacalhau");
        CheckBoxbaca.addActionListener(this::CheckBoxbacaActionPerformed);
        jMenucarda.add(CheckBoxbaca);

        CheckBoxsopa.setText("Sopa");
        CheckBoxsopa.addActionListener(this::CheckBoxsopaActionPerformed);
        jMenucarda.add(CheckBoxsopa);

        jMenuBar1.add(jMenucarda);

        jMenu4.setBackground(new java.awt.Color(204, 204, 255));
        jMenu4.setText("Adicionar");

        Checkbatapalha.setText("Batata palha");
        Checkbatapalha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Checkbatapalha.addActionListener(this::CheckbatapalhaActionPerformed);
        jMenu4.add(Checkbatapalha);

        CheckBoxextra.setText("Arroz Extra");
        CheckBoxextra.addActionListener(this::CheckBoxextraActionPerformed);
        jMenu4.add(CheckBoxextra);

        CheckBoxbata.setText("Batata");
        CheckBoxbata.addActionListener(this::CheckBoxbataActionPerformed);
        jMenu4.add(CheckBoxbata);

        CheckBoxsala.setText("Salada");
        CheckBoxsala.addActionListener(this::CheckBoxsalaActionPerformed);
        jMenu4.add(CheckBoxsala);

        jMenuBar1.add(jMenu4);

        jMenu12.setBackground(new java.awt.Color(255, 204, 255));
        jMenu12.setText("Bebidas");

        CheckBoxcoca.setText("Coca-cola");
        CheckBoxcoca.addActionListener(this::CheckBoxcocaActionPerformed);
        jMenu12.add(CheckBoxcoca);

        CheckBoxagua.setText("Água");
        jMenu12.add(CheckBoxagua);

        CheckBoxguarana.setText("Guaraná");
        jMenu12.add(CheckBoxguarana);

        CheckBoxpedras.setText("Água das Pedras Limao");
        jMenu12.add(CheckBoxpedras);

        CheckBoxnenhu.setText("Nenhum");
        jMenu12.add(CheckBoxnenhu);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Buttonpaga, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Buttondele)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonpaga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buttondele, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxstrogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxstrogoActionPerformed
                                                  
    if (CheckBoxstrogo.isSelected()) {
        // O cliente marcou o prato
        pedidoCliente += "Strogonoff\n";
        valorTotal += 12.00;
        javax.swing.JOptionPane.showMessageDialog(this, "Strogonoff adicionado ao pedido!");
    } else {
        // O cliente desmarcou o prato (subtrai o valor)
        valorTotal -= 12.00;
        javax.swing.JOptionPane.showMessageDialog(this, "Strogonoff removido do pedido.");
    }
    }//GEN-LAST:event_CheckBoxstrogoActionPerformed

    private void CheckBoxextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxextraActionPerformed

    if (CheckBoxextra.isSelected()) {
         pedidoCliente += "Arroz Extra\n";
        valorTotal += 4.00;
        javax.swing.JOptionPane.showMessageDialog(this, "Arroz Extra adicionado ao pedido!");
    } else {
        // O cliente desmarcou o prato
        javax.swing.JOptionPane.showMessageDialog(this, "Arroz Extra removido do pedido.");
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxextraActionPerformed

    private void CheckBoxbacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxbacaActionPerformed
    
    if (CheckBoxbaca.isSelected()) {
       pedidoCliente += "Bacalhau\n";
       valorTotal += 15.00; 
        javax.swing.JOptionPane.showMessageDialog(this, "Bacalhau adicionado ao pedido!");
    } else {
       
        javax.swing.JOptionPane.showMessageDialog(this, "Bacalhau removido do pedido.");
    }

    // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxbacaActionPerformed

    private void CheckBoxsopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxsopaActionPerformed
        // TODO add your handling code here:
    if (CheckBoxsopa.isSelected()) {
      pedidoCliente += "Sopa\n";
      valorTotal += 2.00; 
        javax.swing.JOptionPane.showMessageDialog(this, "Sopa adicionado ao pedido!");
    } else {
       
        javax.swing.JOptionPane.showMessageDialog(this, "Sopa removido do pedido.");
    }    
    }//GEN-LAST:event_CheckBoxsopaActionPerformed

    private void CheckbatapalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckbatapalhaActionPerformed
     
    if (Checkbatapalha.isSelected()) {
      pedidoCliente += "Batata Palha\n";
      valorTotal += 1.00; 
        javax.swing.JOptionPane.showMessageDialog(this, " Batata Palha adicionado ao pedido!");
    } else {
       
        javax.swing.JOptionPane.showMessageDialog(this, "Batata Palha removido do pedido.");
    }    
    // TODO add your handling code here:
    }//GEN-LAST:event_CheckbatapalhaActionPerformed

    private void CheckBoxbataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxbataActionPerformed
     
    if (CheckBoxbata.isSelected()) {
      pedidoCliente += "Batata\n";
      valorTotal += 6.00;
        javax.swing.JOptionPane.showMessageDialog(this, " Batata adicionado ao pedido!");
    } else {
       
        javax.swing.JOptionPane.showMessageDialog(this, "Batata removido do pedido.");
    } 
    // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxbataActionPerformed

    private void CheckBoxsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxsalaActionPerformed
     
    if (CheckBoxsala.isSelected()) {
      pedidoCliente += "Salada\n";
      valorTotal += 3.00;
        javax.swing.JOptionPane.showMessageDialog(this, " Salada adicionado ao pedido!");
    } else {
       
        javax.swing.JOptionPane.showMessageDialog(this, "Salada removido do pedido.");
    } 
    // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxsalaActionPerformed

    private void ButtondeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondeleActionPerformed
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Tem a certeza de que deseja limpar o seu pedido?",
        "Cancelar Pedido",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
        CheckBoxstrogo.setSelected(false);
        CheckBoxbaca.setSelected(false);
        CheckBoxsopa.setSelected(false);

        Checkbatapalha.setSelected(false);
        CheckBoxextra.setSelected(false);
        CheckBoxbata.setSelected(false);
        CheckBoxsala.setSelected(false);

        javax.swing.JOptionPane.showMessageDialog(this, "Pedido cancelado com sucesso.");
    }
     Textresumo.setText("");
    // TODO add your handling code here:
    }//GEN-LAST:event_ButtondeleActionPerformed

    private void ButtonpagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpagaActionPerformed
    StringBuilder resumoPedido = new StringBuilder();
    double total = 0.0;

    if (CheckBoxstrogo.isSelected()) {
        resumoPedido.append("- Strogonoff (12.00 €)\n");
        total += 12.00;
    }
    if (CheckBoxbaca.isSelected()) {
        resumoPedido.append("- Bacalhau (15.00 €)\n");
        total += 15.00;
    }
    if (CheckBoxsopa.isSelected()) {
        resumoPedido.append("- Sopa (2.00 €)\n");
        total += 2.00;
    }

    if (Checkbatapalha.isSelected()) {
        resumoPedido.append("- Batata palha (1.00 €)\n");
        total += 1.00;
    }
    if (CheckBoxextra.isSelected()) {
        resumoPedido.append("- Arroz Extra (4.00 €)\n");
        total += 4.00;
    }
    if (CheckBoxbata.isSelected()) {
        resumoPedido.append("- Batata (6.00 €)\n");
        total += 6.00;
    }
    if (CheckBoxsala.isSelected()) {
        resumoPedido.append("- Salada (3.00 €)\n");
        total += 3.00;
    }
    if (CheckBoxcoca.isSelected()) { 
        resumoPedido.append("- Coca-cola (2.50 €)\n");
        total += 2.50;
    }
    if (CheckBoxagua.isSelected()) { 
        resumoPedido.append("- Água (1.20 €)\n");
        total += 1.20;
    }
    if (CheckBoxguarana.isSelected()) { 
        resumoPedido.append("- Guaraná (2.50 €)\n");
        total += 2.50;
    }
    if (CheckBoxpedras.isSelected()) { 
        resumoPedido.append("- Água das Pedras Limão (2.00 €)\n");
        total += 2.00;
    }

    // 
    if (resumoPedido.length() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione pelo menos um item antes de prosseguir.");
        return;
    }

    
    Textresumo.setText("=== SEU PEDIDO ===\n" + resumoPedido.toString() + "\nTotal: " + total + " €");

    int resposta = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Confirma este pedido para pagamento?\n\n" + resumoPedido.toString() + "\nTotal a Pagar: " + total + " €", 
        "Confirmar Pedido", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );


    }//GEN-LAST:event_ButtonpagaActionPerformed

    private void CheckBoxcocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxcocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxcocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttondele;
    private javax.swing.JButton Buttonpaga;
    private javax.swing.JCheckBoxMenuItem CheckBoxagua;
    private javax.swing.JCheckBoxMenuItem CheckBoxbaca;
    private javax.swing.JCheckBoxMenuItem CheckBoxbata;
    private javax.swing.JCheckBoxMenuItem CheckBoxcoca;
    private javax.swing.JCheckBoxMenuItem CheckBoxextra;
    private javax.swing.JCheckBoxMenuItem CheckBoxguarana;
    private javax.swing.JCheckBoxMenuItem CheckBoxnenhu;
    private javax.swing.JCheckBoxMenuItem CheckBoxpedras;
    private javax.swing.JCheckBoxMenuItem CheckBoxsala;
    private javax.swing.JCheckBoxMenuItem CheckBoxsopa;
    private javax.swing.JCheckBoxMenuItem CheckBoxstrogo;
    private javax.swing.JCheckBoxMenuItem Checkbatapalha;
    private javax.swing.JTextArea Textresumo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenucarda;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
